name: Artículos últimos blog
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1,15 * *'
permissions:
      contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from wordpress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://felepino.org/feed/?api_key=${{ secrets.FEED_API_KEY }}"
